name: Android Build

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ CI/addMavenPublishJob ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Access API Keys
        run: |
            touch local.properties
            echo CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} >> local.properties
            echo CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} >> local.properties
            echo PASS_KEY=${{ secrets.PASS_KEY }} >> local.properties
            cat apikey.properties

      - name: Clean
        run: ./gradlew clean

      - name: Test
        run: ./gradlew -xtest

      - name: Lint Check
        run: ./gradlew -xlint

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Check MavenPublish
        run: ./gradlew publishToMavenLocal

      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
